---
title: "Capstone Proposal Recession"
author: "Daniel Seo"
date: "4/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Springboard Proposal"
author: "Daniel Seo"
date: "4/21/2018"
output: html_document
---

# Springboard Capstone Project

## Introduction: Prediction Model for Next Economic Downturn

Everyone was affected by the economic downturn in 2008 but there were only a small amount of people who saw it coming. They were able to see all the signs that were pointing to a problem that no one else could see. These people were at the right place, at the right time and learned of crucial information to help them figure out for themselves that a recession was imminent. What if there was a way to use data to predict when the next economic downturn would be? This capstone project will allow us to look at certain factors to see when the next one could be.

## Method

### Datasets to consider

Data to consider for this type of predictive model could include many different factors but the following are indicators of a recession. 

  * Unemployment Rate 
  * Credit default/delinquency rates
  * GDP
  * Inflation Rate
  
### Approach

The predictive model will look for correlations between all four data sets compared to when a recession or a depression in the econmy occurred in history. The data sets will be graphed on a plot with year as the X-axis. If possible, using data that will allow quarterly plots would be ideal. Each data set will need to have a upper and lower limit and a median.
  
  * History of Recessions in the United States
    + 1945
    + 1949
    + 1953
    + 1957
    + 1960
    + 1970
    + 1973 - 1975
    + 1980 - 1982
    + 1990 - 1991
    + 2001
    + 2008 - 2009
    
### Deliverables

This capstone project will have a report of the findings as well as graphs in a slide deck showing each data set broken down into specific easy to read graphs. 
